name: Pilates Divita
favicon: null
layout_spectrum: 0.5745632648468018
typography_spectrum: 0.49054198479279876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5861732519697398
  lightness: 0.714814038015902
  saturation: 0.2438361740205437
  rhythmicContrast: 0.5498059059027582
purpose: []
